In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
X = iris.data

In [6]:
y = iris.target

In [7]:
from keras.utils import to_categorical

Using TensorFlow backend.


In [8]:
y = to_categorical(y)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
scaler = MinMaxScaler()

In [13]:
scaler.fit(X_train)

MinMaxScaler()

In [14]:
scaled_X_train = scaler.transform(X_train)

In [15]:
scaled_X_test = scaler.transform(X_test)

In [16]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [17]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [18]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.fit(scaled_X_train, y_train, epochs=150, verbose=2)

Epoch 1/150
 - 0s - loss: 1.1531 - accuracy: 0.3100
Epoch 2/150
 - 0s - loss: 1.1397 - accuracy: 0.3100
Epoch 3/150
 - 0s - loss: 1.1281 - accuracy: 0.3100
Epoch 4/150
 - 0s - loss: 1.1180 - accuracy: 0.3100
Epoch 5/150
 - 0s - loss: 1.1092 - accuracy: 0.3100
Epoch 6/150
 - 0s - loss: 1.1021 - accuracy: 0.3200
Epoch 7/150
 - 0s - loss: 1.0949 - accuracy: 0.3200
Epoch 8/150
 - 0s - loss: 1.0882 - accuracy: 0.3200
Epoch 9/150
 - 0s - loss: 1.0817 - accuracy: 0.3300
Epoch 10/150
 - 0s - loss: 1.0750 - accuracy: 0.3300
Epoch 11/150
 - 0s - loss: 1.0687 - accuracy: 0.3500
Epoch 12/150
 - 0s - loss: 1.0622 - accuracy: 0.3800
Epoch 13/150
 - 0s - loss: 1.0557 - accuracy: 0.4200
Epoch 14/150
 - 0s - loss: 1.0495 - accuracy: 0.4400
Epoch 15/150
 - 0s - loss: 1.0432 - accuracy: 0.4600
Epoch 16/150
 - 0s - loss: 1.0363 - accuracy: 0.5100
Epoch 17/150
 - 0s - loss: 1.0286 - accuracy: 0.5600
Epoch 18/150
 - 0s - loss: 1.0199 - accuracy: 0.6000
Epoch 19/150
 - 0s - loss: 1.0097 - accuracy: 0.6300
Ep

In [20]:
predictions = model.predict_classes(scaled_X_test)
predictions

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 1, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 1, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [21]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [22]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [25]:
print(classification_report(y_test.argmax(axis=1), predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.82      0.93      0.87        15
           2       0.93      0.81      0.87        16

    accuracy                           0.92        50
   macro avg       0.92      0.92      0.91        50
weighted avg       0.92      0.92      0.92        50



In [26]:
print(confusion_matrix(y_test.argmax(axis=1), predictions))

[[19  0  0]
 [ 0 14  1]
 [ 0  3 13]]


In [27]:
print(accuracy_score(y_test.argmax(axis=1), predictions))

0.92


In [28]:
model.save('irismodel.h5')

In [29]:
from keras.models import load_model

In [30]:
new_model = load_model('irismodel.h5')

In [31]:
new_model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 1, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 1, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)